name: ProGamingParts

trigger:
  branches:
    exclude:
    - '*'

parameters:
- name: Target
  type: string
  default: BuildAndTest
  values:
    - BuildAndTest
    - Release

stages:
  - stage: BuildAndTest
    jobs:
      - job: installSDK
        displayName: Starting BuildAndTest stage
        steps:
          - task: UseDotNet@2
            displayName: Installing SDK
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
          - task: NuGetCommand@2
            displayName: 'Restoring nugets'
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: 'Building'
            inputs:
              command: 'build'
              arguments: '--configuration Release'
          - task: DotNetCoreCLI@2
            displayName: 'Testing and Code Coverage'
            inputs:
              command: 'test'
              
          - task: DotNetCoreCLI@2
            condition: and(succeeded(), eq('${{ parameters.Target }}', 'Release'))
            displayName: Preparing code for publish
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '--no-build --configuration Release'
          - task: PublishPipelineArtifact@1
            condition: and(succeeded(), eq('${{ parameters.Target }}', 'Release'))
            displayName: Publishing
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifact: 'ProGamingParts'
              publishLocation: 'pipeline'

  - stage: Release
    condition: and(succeeded(), eq('${{ parameters.Target }}', 'Release'))
    jobs:
      - job: GetAndReleaseArtifact
        displayName: GetAndReleaseArtifact
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Downloading Artifact
            inputs:
              buildType: 'current'
              artifactName: 'ProGamingParts'
              targetPath: '$(Pipeline.Workspace)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'PGPHolyServiceConn'
              appType: 'webApp'
              WebAppName: 'ProGamingParts'
              deployToSlotOrASE: true
              ResourceGroupName: 'HolyCompanyMainRG'
              SlotName: 'production'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'